student_test/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, TemplateView, LogoutView, PasswordResetView, PasswordResetDoneView,\
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeDoneView, PasswordChangeView
from . import views
from django.urls import reverse_lazy
app_name = 'accounts'

urlpatterns = [
    path('users/', views.UserList.as_view(), name='user_list'),

    path('users/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),

    path('login/', LoginView.as_view(template_name='accounts/user-login.html'), name='login'),

    path('profile/', TemplateView.as_view(template_name='accounts/user-profile.html'), name='profile'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('AddUser/', views.CreateUserView.as_view(), name='user_signup'),

    path('UpdateUser/<int:pk>/', views.UpdateUserView.as_view(), name='user_update'),

    path('password-reset/',
         PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
                                   subject_template_name='accounts/password_reset_subject.txt',
                                   email_template_name='accounts/password_reset_email.html',
                                   success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset',),

    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                          success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),

    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password_change/',
         PasswordChangeView.as_view(template_name='accounts/password_change_form.html',
                                    success_url=reverse_lazy('accounts:password_change_done')), name='password_change'),

    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),
]

student_test/student_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import static
from accounts.views import Index
from django.conf import settings


urlpatterns = [
        path('admin/', admin.site.urls),

        path('accounts/', include('accounts.urls')),

        path('students/', include('students.urls')),

        path('media/<path:path>', static.serve, {'document_root': settings.MEDIA_ROOT}),

        path('', Index.as_view(template_name='accounts/index.html'), name='index'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ]+urlpatterns

student_test/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('CreateTest/', views.CreateTest.as_view(), name='create_test'),

    path('CreateQuestion/<int:pk>/', views.CreateQuestion.as_view(), name='create_question'),

    path('Testlist/', views.TestList.as_view(), name='test_list'),

    path('DeleteTest/<int:pk>/', views.DeleteTest.as_view(), name='delete_test'),

    path('TestView/<int:pk>/', views.TestDetail.as_view(), name='update_test'),

    path('DeleteQuestion/<int:pk>/', views.DeleteQuestion.as_view(), name='delete_question'),

    path('ExamAttempt/<int:test_id>/', views.ExamAttemptView.as_view(), name='exam_test'),

    path('PerformanceDetails/', views.PerformanceDetails.as_view(), name='performance_details'),

    path('TestPerformances/', views.TestDetail.as_view(), name='test_performances'),
]

student_test/accounts/views.py
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from django.views.generic import CreateView, DetailView, TemplateView, UpdateView, ListView


class CreateUserView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """
    View for creating admin,staffs & students
    , which is done by the staffs with admin privileges.
    """
    model = User
    template_name = 'accounts/user-signup.html'
    success_url = reverse_lazy('accounts:user_signup')
    fields = ['first_name', 'last_name', 'username', 'email', 'password', 'is_superuser', 'is_staff']

    def test_func(self):
        """
        :return: Returns only if the user is admin .
        """
        return self.request.user.is_superuser

    def form_valid(self, form):
        """
        Function for overriding the form and saving it.
        :param form: Saving the user sign up form .
        :return: Returns to the success page.
        """
        User.objects.create_user(**form.cleaned_data)
        return redirect(self.success_url)


class UserDetail(DetailView):
    """
    View for showing the detail details.
    """
    model = User
    template_name = 'accounts/user-detail.html'
    context_object_name = 'user_profile'


class UserList(ListView):
    """
    View for showing the list of users.
    """
    model = User
    template_name = 'accounts/user-list.html'
    context_object_name = 'users'

    def get_queryset(self):
        """
        Function for overriding queryset to get filtered data .
        :return: returns the data available in the list.
        """
        queryset = User.objects.all()

        term = self.request.GET.get('term')
        if term:
            queryset = queryset.filter(Q(first_name__icontains=term) | Q(last_name__contains=term))

        return queryset


class UpdateUserView(UpdateView):
    """
    View for updating the user details.
    """
    model = User
    fields = ['first_name', 'last_name', 'username', 'email', 'is_superuser', 'is_staff']
    template_name = 'accounts/user-update.html'
    success_url = reverse_lazy('accounts:user_list')


class Index(TemplateView):
    """
    View for showing the index of the application
    """
    model = User
    template_name = 'accounts/index.html'

student_test/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="background-color:#FFFFF">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="active" style="font-size:40px;font-color:#077E9B" href="">Test Management</a>
        </div>
        <ul class="nav navbar-nav">
            <li>
                <a href="/">Home</a>
            </li>
            {% if user.is_active %}
            <li>
                <a href="{% url 'accounts:profile' %}"><span class="glyphicon glyphicon-user"></span>{{ user.username }}</a>
            </li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_staff %}
            <li>
                <a href="{% url 'accounts:user_list' %}"><span class="glyphicon glyphicon-search"></span> Search Users</a>
            </li>
            {% endif %}
            <li>
                <a href="{% url 'students:test_list' %}"><span class="glyphicon glyphicon-search"></span> Search Test</a>
            </li>
            {% if not user.is_authenticated %}
            <li>
                <a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span> LOGIN</a>
            </li>
            {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span> LOGOUT</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

student_test/accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}

{% block content %}

<h1>Home</h1>
<hr />
{% if user.is_authenticated %}
<p>
	{% if user.is_superuser %}
	<a class="btn btn-primary" href="{% url 'accounts:user_signup' %}"><span class="glyphicon glyphicon-plus"></span>Add user</a>
	<a class="btn btn-danger" href="{% url 'students:create_test' %}"><span class="glyphicon glyphicon-plus"></span>create test</a>
	<a class="btn btn-primary" href="{% url 'accounts:password_change' %}">change password</a>
</p>
<p>
	{% elif user.is_staff %}
	<a class="btn btn-danger" href="{% url 'students:create_test' %}"><span class="glyphicon glyphicon-plus"></span>create test</a>
	<a class="btn btn-primary" href="{% url 'accounts:password_change' %}">change password</a>
</p>
<p>
	{% else %}
	<a class="btn btn-danger" href="{% url 'students:test_list' %}">take test</a>
	<a class="btn btn-primary" href="{% url 'students:performance_details' %}">Performance Details</a>
	<a class="btn btn-primary" href="{% url 'accounts:password_change' %}">change password</a>
	{% endif %}
</p>
{% endif %}
{% if not user.is_authenticated %}<p>Please login</p>{% endif %}
<hr />

{% endblock content%}

student_test/accounts/templates/accounts/password_change_done.html
{% extends 'accounts/base.html' %}
{% block content %}
<p> you have successfully changed you password<a type="button" class="btn btn-secondary" href="/">Exit</a></p>
{% endblock content %}

student_test/accounts/templates/accounts/password_change_form.html
{% extends 'accounts/base.html' %}
{% block content %}
<div  class="card">
<div  class="card-body">
<h4  class="card-title"> Change your password</h4>

<form  method="post">
{% csrf_token %}
{{ form.as_p }}

<button  type="submit"  class="btn btn-success">Change password </button>
</form>
</div>
</div>
{% endblock content%}

student_test/accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/base.html' %}

{% block content %}
  <p>
    Your password has been set. You may go ahead and <a href="{% url 'accounts:login' %}">sign in</a> now.
  </p>
{% endblock %}

student_test/accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base.html' %}

{% block content %}
  {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
{% endblock %}

student_test/accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

student_test/accounts/templates/accounts/password_reset_form.html
{% extends 'accounts/base.html' %}

{% block content %}
  <h3>Forgot password</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

student_test/accounts/templates/accounts/user-detail.html
{% extends 'accounts/base.html' %}

{% block content %}

<h1>{{ user_profile.get_full_name }}</h1>
<hr />
<table class="table table-bordered">
	<tr>
		<td>Name</td>
		<td>{{ user_profile.get_full_name}}</td>
	</tr>
	<tr>
		<td>Email</td>
		<td>{{ user_profile.email }}</td>
	</tr>
	<tr>
		<td>Username</td>
		<td>{{ user_profile.username }}</td>
	</tr>
	<tr>
		<td>Status</td>
		{% if user_profile.is_superuser %}
		<td>Admin</td>
		{% elif user_profile.is_staff %}
		<td>Staff</td>
		{% else %}<td>Student</td>
		{% endif %}
	</tr>
</table>
<hr/>
{%if user.is_superuser %}
<p><a type="button" class="btn btn-primary" href="{% url 'accounts:user_update' pk=user_profile.id %}">Updateuser</a></p>
{% endif %}

{% endblock content %}

student_test/accounts/templates/accounts/user-list.html
{% extends 'accounts/base.html' %}

{% block content %}

<h1 class="text-center">Users</h1>
<hr />
<form>
	<input type="search" name="term" />
	<button type="submit">Search</button>
</form>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Email</th>
			<th>status</th>
		</tr>
	</thead>
	<tbody>
	{% for u in users %}
		<tr>
			<td>{{ u.id }}</td>
			<td>
				<a href="{% url 'accounts:user_detail' pk=u.id %}">{{ u.get_full_name }}</a>
			</td>
			<td>{{ u.email }}</td>
			{% if u.is_superuser %}
			<td>Admin</td>
			{% elif u.is_staff %}
			<td>Staff</td>
			{% else %}
			<td>Student</td>
			{% endif %}
		</tr>
	{% endfor %}
	</tbody>
</table>
<script>
function status(){
var x =document.getElementById("status").text
if u.is_superuser
	document.getElementById("status").text=
</script>

{% endblock content %}

student_test/accounts/templates/accounts/user-login.html
{% extends "accounts/base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}

<form method="post" action=>
{% csrf_token %}
    <h1>Login</h1>
<table>
    <tr>
        <td><p>{{ form.username.label_tag }}</p></td>
        <td><p>{{ form.username }}</p></td>
    </tr>
    <tr>
        <td><p>{{ form.password.label_tag }}</p></td>
        <td><p>{{ form.password }}</p></td>
    </tr>
</table>

<button type="submit" class="btn btn-success" >login</button>
    <a type="button" class="btn btn-secondary" href="{% url 'accounts:password_reset'%}">Forgotpassword</a>
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock content%}

student_test/accounts/templates/accounts/user-profile.html
{% extends "accounts/base.html"%}
{% block content %}

<h1>
    {{ user.username }}</h1>
<hr />
<table class="table table-bordered">
	<tr>
		<td>Name</td>
		<td>{{ user.get_full_name}}</td>
	</tr>
	<tr>
		<td>Email</td>
		<td>{{ user.email }}</td>
	</tr>
	<tr>
		<td>Username</td>
		<td>{{ user.username }}</td>
	</tr>
	<tr>
		<td>Status</td>
		{% if user.is_superuser %}
		<td>
			Admin
		</td>
		{% elif user.is_staff %}
		<td>Staff</td>
		{% else %}
		<td>Student</td>{% endif %}
	</tr>
</table>

{% endblock content %}

student_test/accounts/templates/accounts/user-signup.html
{% extends 'accounts/base.html' %}

{% block title %}Add User{% endblock %}

{% block content %}

<h2>Add User</h2>
<form  method="post">
    <div class="container">
        <div class="col-md-6">
          {% csrf_token %}

            <div  class="form-group ">
                <label for="id_first_name">First name:</label>
                <input type="text"  class="form-control" name="first_name" maxlength="30" required id="id_first_name">
            </div>

            <div class="form-group">
                <label for="id_last_name">Last name:</label>
                <input type="text" class="form-control" name="last_name" maxlength="150" required id="id_last_name">
            </div>

            <div  class="form-group ">
                <label for="id_username">Username:</label>
                <input type="text"  class="form-control" name="username" maxlength="150" required id="id_username">
                <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
            </div>

            <div  class="form-group " >
                <label for="id_email">Email address:</label>
                <input type="email"  class="form-control" name="email" maxlength="254" required id="id_email">
            </div>

            <div  class="form-group" >
                <label for="id_password">Password:</label>
                <input type="password" class="form-control" name="password" maxlength="128" required id="id_password">
            </div>

            <div  class="form-group" >
                <label for="id_is_superuser">Admin:</label>
                <input type="checkbox" name="is_superuser" id="id_is_superuser">
                <span class="helptext">Designates that this user has all permissions without explicitly assigning them.</span>
            </div>

            <div  class="form-group" >
                <label for="id_is_staff">Staff:</label>
                <input type="checkbox" name="is_staff" id="id_is_staff">
                <span class="helptext">Designates whether the user can log into this admin site.</span>
            </div>

            <div class="form-group ">
                <input type="checkbox" onclick="myFunction()">Show Password
            </div>

            <button type="submit" class="btn btn-secondary" >Add User</button>
        </div>
    </div>
</form>
<script>
    function myFunction() {
    var x = document.getElementById("id_password");
    if (x.type === "password") {
      x.type = "text";
    } else {
      x.type = "password";
    }
  }
</script>

{% endblock %}

student_test/accounts/templates/accounts/user-update.html
{% extends 'accounts/base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success" >Update</button>
</form>

{% endblock content %}