student_test/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, TemplateView, LogoutView, PasswordResetView, PasswordResetDoneView,\
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeDoneView, PasswordChangeView
from . import views
from django.urls import reverse_lazy
app_name = 'accounts'

urlpatterns = [
    path('users/', views.UserList.as_view(), name='user_list'),

    path('users/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),

    path('login/', LoginView.as_view(template_name='accounts/user-login.html'), name='login'),

    path('profile/', TemplateView.as_view(template_name='accounts/user-profile.html'), name='profile'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('AddUser/', views.CreateUserView.as_view(), name='user_signup'),

    path('UpdateUser/<int:pk>/', views.UpdateUserView.as_view(), name='user_update'),

    path('password-reset/',
         PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
                                   subject_template_name='accounts/password_reset_subject.txt',
                                   email_template_name='accounts/password_reset_email.html',
                                   success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset',),

    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                          success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),

    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password_change/',
         PasswordChangeView.as_view(template_name='accounts/password_change_form.html',
                                    success_url=reverse_lazy('accounts:password_change_done')), name='password_change'),

    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),
]

student_test/student_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import static
from accounts.views import Index
from django.conf import settings


urlpatterns = [
        path('admin/', admin.site.urls),

        path('accounts/', include('accounts.urls')),

        path('students/', include('students.urls')),

        path('media/<path:path>', static.serve, {'document_root': settings.MEDIA_ROOT}),

        path('', Index.as_view(template_name='accounts/index.html'), name='index'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ]+urlpatterns

student_test/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('CreateTest/', views.CreateTest.as_view(), name='create_test'),

    path('CreateQuestion/<int:pk>/', views.CreateQuestion.as_view(), name='create_question'),

    path('Testlist/', views.TestList.as_view(), name='test_list'),

    path('DeleteTest/<int:pk>/', views.DeleteTest.as_view(), name='delete_test'),

    path('TestView/<int:pk>/', views.TestDetail.as_view(), name='update_test'),

    path('DeleteQuestion/<int:pk>/', views.DeleteQuestion.as_view(), name='delete_question'),

    path('ExamAttempt/<int:test_id>/', views.ExamAttemptView.as_view(), name='exam_test'),

    path('PerformanceDetails/', views.PerformanceDetails.as_view(), name='performance_details'),

    path('TestPerformances/', views.TestDetail.as_view(), name='test_performances'),
]

student_test/students/models.py
from django.db import models


class Test(models.Model):
    """

    """
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, db_index=True)
    test_name = models.CharField(max_length=100)
    slug = models.SlugField()
    published_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.test_name


class Question(models.Model):
    """
    
    """
    question = models.CharField(max_length=300)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    answer = models.CharField(max_length=200)
    choice_1 = models.CharField(max_length=200)
    choice_2 = models.CharField(max_length=200)
    choice_3 = models.CharField(max_length=200)
    created_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.question)


class TestAttempt(models.Model):
    """
    model for attempting a test
    """
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, db_index=True)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    marks = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    class Meta:
        unique_together = ('user', 'test')

    def __str__(self):
        return self.marks

student_test/students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from . models import Test, Question, TestAttempt
from django.urls import reverse_lazy, reverse


class TestList(generic.ListView):
    """
    View for showing the list of test available
    """
    model = Test
    template_name = 'students/test-list.html'
    context_object_name = 'tests'
    queryset = Test.objects.all().order_by('-published_on').select_related('user')


class CreateTest(LoginRequiredMixin, generic.CreateView):
    """
    View for creating new tests.
    """
    model = Test
    fields = ('test_name',)
    template_name = 'students/create-test.html'
    success_url = reverse_lazy('students:test_list')

    def form_valid(self, form):
        """
        Function for overriding the form and saving it.
        :param form: saving a new test object.
        :return: returns to the success page.
        """
        test = form.save(commit=False)
        test.user = self.request.user
        test.save()
        return redirect(self.success_url)


class CreateQuestion(LoginRequiredMixin, generic.CreateView, generic.ListView):
    """
    View for creating the questions in a test.
    """
    model = Question
    fields = ('question', 'answer', 'choice_1', 'choice_2', 'choice_3')
    template_name = 'students/add-question.html'
    context_object_name = 'questions'

    def form_valid(self, form):
        """
        Function for overriding the form and saving it.
        :param form: Saving the question and choices in a test.
        :return: Returns to the success page.
        """
        question = form.save(commit=False)
        test_id = self.kwargs['pk']
        test = Test.objects.get(id=test_id)
        if test.user == self.request.user:
            question.test = test
            question.save()
        return redirect(reverse('students:create_question', kwargs={'pk': test_id}))


class DeleteTest(LoginRequiredMixin, generic.DeleteView):
    """
    View for deleting a test.
    """
    model = Test
    template_name = 'students/delete-TestOrQuestion.html'
    success_url = reverse_lazy('students:test_list')


class TestDetail(generic.DetailView):
    """
    Showing the details of a test in a detail view, which shows both questions and choices
    """
    model = Test
    template_name = 'students/test-detail.html'
    context_object_name = 'test'
    queryset = Test.objects.all().order_by('-published_on').select_related('user')


class DeleteQuestion(generic.DeleteView):
    """
    View for deleting a question in a test
    """
    model = Question
    template_name = 'students/delete-TestOrQuestion.html'
    success_url = reverse_lazy('students:test_list')


class ExamAttemptView(LoginRequiredMixin, generic.View):
    """
    class based view for a student when student attempt a test.
    """
    context_object_name = 'attempt'

    def get(self, request, test_id):
        """
        Function for getting the data from a particular test
        :param request: Request for getting the data
        :param test_id: The id which is passed in the url for getting the data from a particular test
        :return: Either returns to the page showing the question just after starting the exam or
         showing the result of test if user tries to attempt the test again
        """
        test = get_object_or_404(Test, id=test_id)

        test_attempt, created = TestAttempt.objects.get_or_create(test=test, user=request.user)

        if created:
            questions = test.question_set.all().values_list('id', flat=True)
            request.session['questions'] = list(questions)
            questions = request.session['questions']
            current_question_id = questions.pop()
            request.session['current_question'] = current_question_id
            current_question = Question.objects.get(id=current_question_id)
        else:
            if test_attempt.is_active is False:
                return render(request, 'students/result.html', {'marks': test_attempt.marks})
            questions = request.session['questions']
            current_question = Question.objects.get(id=request.session['current_question'])

        return render(request, 'students/exam-attempt.html', {
            'question': current_question,
        })

    def post(self, request, test_id):
        """
        Function for submitting the answer of the question
        :param request: Request for posting the data
        :param test_id: The id which is passed in the url for getting the data from a particular test
        :return: Either returns to the success page after just completing the exam or
         showing the result of test if user tries to attempt the test again
        """
        test = get_object_or_404(Test, id=test_id)
        test_attempt = TestAttempt.objects.get(test=test, user=request.user)
        questions = request.session['questions']
        current_question = Question.objects.get(id=request.session['current_question'])
        answer = request.POST.get('answer')

        if answer == current_question.answer:
            test_attempt.marks = test_attempt.marks + 2
            test_attempt.save()
        else:
            test_attempt.marks = test_attempt.marks - 1
            test_attempt.save()

        if not questions:
            test_attempt.is_active = False
            test_attempt.save()
            return render(request, 'students/result.html', {'marks': test_attempt.marks})

        next_question_id = questions.pop()
        next_question = Question.objects.get(id=next_question_id)
        request.session['questions'] = questions
        request.session['current_question'] = next_question_id
        return render(request, 'students/exam-attempt.html', {
            'question': next_question,
        })


class PerformanceDetails(generic.ListView):
    """
    view for showing a student their performance details of the tests they have attempted.
    """
    model = TestAttempt
    template_name = 'students/performance_details.html'
    context_object_name = 'test_attempt'

    def get_queryset(self):
        """
        to get list of data of a particular user.
        :return: returns the list of data
        """
        queryset = TestAttempt.objects.filter(user=self.request.user).select_related('user', 'test')

        return queryset

student_test/students/templates/students/add-question.html
{% extends 'accounts/base.html' %}
{% block content %}

<h2>Create Question</h2>
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-default">Create</button>
        <a type="button" class="btn btn-primary" href="{% url 'students:test_list'%}">Go Back</a>
    </form>
<hr/>

{% endblock content %}

student_test/students/templates/students/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'accounts/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="background-color:#FFFFF">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="active" style="font-size:40px;font-color:#077E9B" href="">Test Management</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span>{{ user.username }}</a></li>
    </ul>
  </div>
</nav>
<div class="container">
	{% block content %}{% endblock content %}
</div>
</body>
</html>

student_test/students/templates/students/create-test.html
{% extends 'accounts/base.html' %}
{% block content %}

<h2>Create Test</h2>
    <form method="post" class="form-inline">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-default">Create</button>
    </form>

{% endblock content %}

student_test/students/templates/students/delete-TestOrQuestion.html
{% extends 'accounts/base.html' %}

{% block content %}

<form method="post">
	{% csrf_token %}
    <p>Are you sure?</p>
	<button type="submit" class="btn btn-success">Delete</button>
</form>

{% endblock content %}

student_test/students/templates/students/exam-attempt.html
{% extends 'students/base.html' %}
{% block content %}

<p>{{ question.question }}</p>
<form method="post">
  {% csrf_token %}
  <input name="answer" value="{{ question.choice_1 }}" type="radio">{{ question.choice_1 }}
  <br />
  <input name="answer" value="{{ question.choice_2 }}" type="radio">{{ question.choice_2 }}
  <br />
  <input name="answer" value="{{ question.choice_3 }}" type="radio">{{ question.choice_3 }}
  <br />
  <button type="submit">Submit</button>
</form>

{% endblock content %}

student_test/students/templates/students/performance_details.html
{% extends 'accounts/base.html' %}

{% block content %}

<table class="table table-bordered">
    <thead>
   <tr>
       <th>Test</th>
       <th>Score</th>
   </tr>
   </thead>
    <tbody>
    {% for attempt in test_attempt %}
    <tr>
       <td>{{attempt.test.test_name }}</td>
       <td>{{ attempt.marks }}</td>
       {% empty %}
    <tr>
    <td colspan="2">no test attempt</td>
</tr>
     {% endfor %}
    </tbody>
 </table>

{% endblock content %}

student_test/students/templates/students/result.html
{% extends 'students/base.html' %}
{% block content %}

{% if not attempt.is_active %}
<p>you have completed the test and the marks :{{marks}}</p>
{% endif %}
<p><a type="button" class="btn btn-secondary" href="{% url 'students:test_list' %}">Exit</a></p>

{% endblock content %}

student_test/students/templates/students/test-detail.html
{% extends 'accounts/base.html' %}

{% block content %}

<h1>Test: {{test.test_name}}</h1>
<hr/>
{% if user.username == test.user.username or user.is_superuser %}
<a class="btn btn-success" href="{% url 'students:create_question' pk=test.id %}"><span class="glyphicon glyphicon-plus"></span>Add Question</a>
{% endif %}
<hr/>
<h3>Test Details</h3>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Student name</th>
        <th>marks</th>
    </tr>
    </thead>
    <tbody>
    {% for attempt in test.testattempt_set.all %}
    <tr>
        <td>{{ attempt.user.get_full_name }}</td>
        <td>{{ attempt.marks }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<hr/>
<h3>Questions Available</h3>
<hr/>
{% for question in test.question_set.all %}
<p>Question : {{question.question}}</p>
<p>Choice1 : {{question.choice_1}}</p>
<p>Choice2 : {{question.choice_2}}</p>
<p>Choice3 : {{question.choice_3}}</p>
{% if user.username == test.user.username or user.is_superuser %}
<a class="btn btn-danger" href="{% url 'students:delete_question' pk=question.id %}">Delete</a>
{% endif %}
<hr/>
{% empty %}
<p>No questions</p>
{% endfor%}

{% endblock content%}

student_test/students/templates/students/test-list.html
{% extends 'accounts/base.html' %}

{% block content %}

	<h1>Tests</h1>
	<hr />
	<p>
		{% if user.is_staff %}<a class="btn btn-danger" href="{% url 'students:create_test' %}">New Test</a>{% endif %}
	</p>

<table class="table table-bordered">
	<thead>
	<tr>
		<th>Test published on:</th>
		<th>Test name:</th>
		{% if user.is_active%}
		<th>Action</th>
		{% endif %}
	</tr>
	</thead>
	<tbody>
		{% for test in tests %}
	<tr>
		<td>{{ test.published_on }}</td>
		<td>{{ test.test_name }}</td>
		{% if user.is_active%}
		<td>
			{% if user.is_staff %}
			<p>
				<a class="btn btn-success" href="{% url 'students:update_test' pk=test.id %}">View/Add Question</a>
				{% if user.username == test.user.username or user.is_superuser %}
				<a class="btn btn-danger" href="{% url 'students:delete_test' pk=test.id %}">Delete</a>
				{% endif %}
				{% else %}
				<a class="btn btn-success" href="{% url 'students:exam_test' test.id %}">Attempt Test</a>
				{% endif %}
			</p>
		</td>
		{% endif %}
		{% empty %}
		<td colspan="2">No tests</td>
	</tr>
	{% endfor %}
	</tbody>
</table>

{% endblock content %}